INSERT INTO quizzforall.question (text, quiz_id, created_at, updated_at) VALUES ('Which sport is known as "the beautiful game"?',4,'2023-02-14','2023-02-14');
INSERT INTO quizzforall.question (text, quiz_id, created_at, updated_at) VALUES ('In which year was the first modern Olympic Games held?',4,'2023-02-14','2023-02-14');
INSERT INTO quizzforall.question (text, quiz_id, created_at, updated_at) VALUES ('What is the standard number of players on a baseball team?',4,'2023-02-14','2023-02-14');
INSERT INTO quizzforall.question (text, quiz_id, created_at, updated_at) VALUES ('Who holds the record for the most Grand Slam tennis titles won by a male player?',4,'2023-02-14','2023-02-14');
INSERT INTO quizzforall.question (text, quiz_id, created_at, updated_at) VALUES ('Which country has won the most FIFA World Cup titles?',4,'2023-02-14','2023-02-14');
INSERT INTO quizzforall.question (text, quiz_id, created_at, updated_at) VALUES ('In American football, how many points is a touchdown worth?',4,'2023-02-14','2023-02-14');
INSERT INTO quizzforall.question (text, quiz_id, created_at, updated_at) VALUES ('Who is often referred to as "The Greatest" in the world of boxing?',4,'2023-02-14','2023-02-14');
INSERT INTO quizzforall.question (text, quiz_id, created_at, updated_at) VALUES ('Which of the following is NOT a type of wrestling in the Olympic Games?',4,'2023-02-14','2023-02-14');
INSERT INTO quizzforall.question (text, quiz_id, created_at, updated_at) VALUES ('Which sport uses the terms "birdie" and "eagle" to describe scores?',4,'2023-02-14','2023-02-14');
INSERT INTO quizzforall.question (text, quiz_id, created_at, updated_at) VALUES ('What is the longest distance in meters for an official marathon race?',4,'2023-02-14','2023-02-14');
