INSERT INTO quizzforall.question (id, text, quiz_id, created_at, updated_at) VALUES (14,'Qui était le roi de France pendant la Révolution française',5,'2023-02-14','2023-02-14');
INSERT INTO quizzforall.question (id, text, quiz_id, created_at, updated_at) VALUES (15,'En quelle année a eu lieu la bataille de Poitiers pendant la guerre de Cent Ans ',5,'2023-02-14','2023-02-14');
INSERT INTO quizzforall.question (id, text, quiz_id, created_at, updated_at) VALUES (16,'Quelle reine de France était surnommée "la Reine autrichienne" avant la Révolution ?',5,'2023-02-14','2023-02-14');
INSERT INTO quizzforall.question (id, text, quiz_id, created_at, updated_at) VALUES (17,'Qui a dirigé la Résistance française pendant la Seconde Guerre mondiale ?',5,'2023-02-14','2023-02-14');
INSERT INTO quizzforall.question (id, text, quiz_id, created_at, updated_at) VALUES (18,'Quelle bataille médiévale a mis fin à la dynastie mérovingienne en France ?',5,'2023-02-14','2023-02-14');
INSERT INTO quizzforall.question (id, text, quiz_id, created_at, updated_at) VALUES (19,'Qui a écrit le livre "Les Misérables", qui se déroule en France au XIXe siècle ?',5,'2023-02-14','2023-02-14');
INSERT INTO quizzforall.question (id, text, quiz_id, created_at, updated_at) VALUES (20,'En quelle année a eu lieu la Révolution de 1789 en France ?',5,'2023-02-14','2023-02-14');
INSERT INTO quizzforall.question (id, text, quiz_id, created_at, updated_at) VALUES (21,'Qui était le roi de France pendant la construction de la cathédrale Notre-Dame de Paris ?',5,'2023-02-14','2023-02-14');
INSERT INTO quizzforall.question (id, text, quiz_id, created_at, updated_at) VALUES (22,'Quel empereur français a été exilé sur l''ile dElbe avant son retour pour les Cent-Jours ?',5,'2023-02-14','2023-02-14');
INSERT INTO quizzforall.question (id, text, quiz_id, created_at, updated_at) VALUES (23,'Quel événement historique français est associé à la prise de la Bastille ?',5,'2023-02-14','2023-02-14');
